In [1]:
import pandas as pd
# anno_1 = '../Human_anno/humananno_res/lsy_scene.xlsx'
# anno_2 = '../Human_anno/humananno_res/lsy_scene.xlsx'

# anno_1oc =pd.read_excel(anno_1, usecols=['Model','scene'])
# anno_2oc =pd.read_excel(anno_2, usecols=['Model','scene'])
# anno_1oc = anno_1oc.astype(object).where(pd.notnull(anno_1oc), None)
# anno_2oc = anno_2oc.astype(object).where(pd.notnull(anno_2oc), None)

In [2]:
import numpy as np
    
def rank_numbers(numbers):
    sorted_indices = sorted(range(len(numbers)), key=lambda k: numbers[k], reverse=True)
    ranks = [0] * len(numbers)

    i = 0
    while i < len(sorted_indices):
        value_indices = [i]
        while i + 1 < len(sorted_indices) and numbers[sorted_indices[i]] == numbers[sorted_indices[i + 1]]:
            i += 1
            value_indices.append(i)
        average_rank = np.mean([index + 1 for index in value_indices])
        for index in value_indices:
            ranks[sorted_indices[index]] = average_rank
        i += 1

    return ranks

def calculate_spearman_manual(values1, values2):
    n = len(values1)
    m = len(values2)
    rank1 = rank_numbers(values1)
    rank2 = rank_numbers(values2)
    d = np.array(rank1) - np.array(rank2)
    d_squared = np.square(d)
    spearman_corr = 1 - (6 * np.sum(d_squared)) / (n * (n**2 - 1))
    return spearman_corr

def rank_basescore(base_score, draw_ratio):
    # 计算最大值和最小值的差值
    score_range = max(base_score) - min(base_score)
    # 计算平序的阈值
    draw_gap = draw_ratio * score_range

    # 对列表进行排序并保留原始索引
    indexed_scores = list(enumerate(base_score))
    indexed_scores.sort(key=lambda x: x[1])

    # 处理平序
    ranks = [0] * len(base_score)
    current_rank = 1
    for i in range(len(indexed_scores)):
        if i > 0 and abs(indexed_scores[i][1] - indexed_scores[i - 1][1]) < draw_gap:
            ranks[indexed_scores[i][0]] = current_rank
        else:
            current_rank = i + 1
            ranks[indexed_scores[i][0]] = current_rank

    return ranks

In [3]:
dimension = 'color'

In [4]:
import json
jsonpath = '../Human_anno/{}.json'.format(dimension)
with open(jsonpath,'r') as f:
    oc = json.load(f)

# history ="../GPT4o_eval_results/{}_gpt4eval_results.json".format(dimension)
# with open(history,'r') as f:
#     gpt4o_eval_history = json.load(f)

In [5]:
# gptvsanno1_spearman = 0
# gptvsanno2_spearman = 0
# anno1vsanno2_spearman = 0
# gptvsannomean = 0
# badeval = []

# for i in range(length):
#     if i % 3 == 0:
#         gpt4o_eval_rs = np.array(list(oc[i]['gpt4o_eval'].values()))
#         human_anno = np.array(list(oc[i]['human_anno'].values()))
#         anno1 = human_anno[:,0]
#         anno2 = human_anno[:,1]
#         annomean = (anno1 + anno2)/2
#     else:
#         gpt4o_eval_rs+= np.array(list(oc[i]['gpt4o_eval'].values()))
#         human_anno = np.array(list(oc[i]['human_anno'].values()))
#         anno1 += human_anno[:,0]
#         anno2 += human_anno[:,1]
#         annomean += (anno1 + anno2)/2

#     if i % 3 == 2:
#         gptvsanno1_spearman += calculate_spearman_manual(gpt4o_eval_rs,anno1)
#         gptvsanno2_spearman += calculate_spearman_manual(gpt4o_eval_rs,anno2)
#         anno1vsanno2_spearman += calculate_spearman_manual(anno1,anno2)
#         gptvsannomean += calculate_spearman_manual(gpt4o_eval_rs,annomean)

# gptvsanno1_spearman = 3*gptvsanno1_spearman/length
# gptvsanno2_spearman = 3*gptvsanno2_spearman/length
# anno1vsanno2_spearman = 3*  anno1vsanno2_spearman/length
# gptvsannomean = 3*gptvsannomean/length
# print("GPT vs Anno1 Spearman: ",gptvsanno1_spearman)
# print("GPT vs Anno2 Spearman: ",gptvsanno2_spearman)
# print("Anno1 vs Anno2 Spearman: ",anno1vsanno2_spearman)
# print("GPT vs AnnoMean Spearman: ",gptvsannomean)

In [6]:
models = ['cogvideox5b','gen3', 'kling','videocrafter2', 'pika', 'show1', 'lavie']
# models = ['videocrafter2', 'pika', 'show1', 'lavie']
# models = ['cogvideox5b','gen3', 'kling']
idexls = []
for i in range(0,len(oc),3):
    idexls.append(i)
# for i in range(1,len(oc),3):
#     idexls.append(i)
length = len(idexls)

In [7]:
gptvsanno1_spearman = np.zeros(length)
gptvsanno2_spearman = np.zeros(length)
anno1vsanno2_spearman = np.zeros(length)
gptvsannomean_spearman = np.zeros(length)
baselinevsanno1_spearman = np.zeros(length)
baselinevsanno2_spearman = np.zeros(length)
baselinevsannomean_spearman = np.zeros(length)

gptscore = np.zeros([len(models)])
anno1score = np.zeros([len(models)])
anno2score = np.zeros([len(models)])
annomeanscore =np.zeros([len(models)])
baseline_rank = np.zeros([7])
badeval = []

for j in range(length):
    i = idexls[j]
    gpt4o_eval_rs = np.array(list(oc[i]['gpt4o_eval'].values()))
    human_anno = np.array(list(oc[i]['human_anno'].values()))
    baseline_score = np.array(list(oc[i]['baseline_score'].values()))


    anno1 = human_anno[:,1]
    anno2 = human_anno[:,2]

    anno1[anno1 == 2] = 1
    anno1[anno1 == 3] = 2
    anno1[anno1 == 5] = 3
    anno1[anno1 == 4] = 3

    anno2[anno2 == 2] = 1
    anno2[anno2 == 3] = 2
    anno2[anno2 == 4] = 3
    anno2[anno2 == 5] = 3

    annomean = (anno1 + anno2)/2


    gptscore += gpt4o_eval_rs
    anno1score += anno1
    anno2score += anno2
    annomeanscore += annomean
    baseline_rank += rank_basescore(baseline_score, 0.2)


    gptvsanno1 = calculate_spearman_manual(gpt4o_eval_rs,anno1)
    gptvsanno2 = calculate_spearman_manual(gpt4o_eval_rs,anno2)
    anno1vsanno2 = calculate_spearman_manual(anno1,anno2)
    gptvsannomean = calculate_spearman_manual(gpt4o_eval_rs,annomean)
    baselinevsanno1 = calculate_spearman_manual(baseline_rank,anno1)
    baselinevsanno2 = calculate_spearman_manual(baseline_rank,anno2)
    baselinevsannomean = calculate_spearman_manual(baseline_rank,annomean)

    # j = i
    gptvsanno1_spearman[j] = gptvsanno1
    gptvsanno2_spearman[j] = gptvsanno2
    anno1vsanno2_spearman[j] = anno1vsanno2
    gptvsannomean_spearman[j] = gptvsannomean
    baselinevsanno1_spearman[j] = baselinevsanno1
    baselinevsanno2_spearman[j] = baselinevsanno2
    baselinevsannomean_spearman[j] = baselinevsannomean

    if gptvsanno1 <0.2:
        badeval.append(i)

gptscore = gptscore/length
anno1score = anno1score/length
anno2score = anno2score/length
annomeanscore = annomeanscore/length

print("GPT vs Anno1 Spearman: ",gptvsanno1_spearman.mean())
print("GPT vs Anno2 Spearman: ",gptvsanno2_spearman.mean())
print("Anno1 vs Anno2 Spearman: ",anno1vsanno2_spearman.mean())
print("GPT vs AnnoMean Spearman: ",gptvsannomean_spearman.mean())
print("Baseline vs Anno1 Spearman: ",baselinevsanno1_spearman.mean())
print("Baseline vs Anno2 Spearman: ",baselinevsanno2_spearman.mean())
print("Baseline vs AnnoMean Spearman: ",baselinevsannomean_spearman.mean())


print("GPT average score: ",gptscore)
print("Anno1 average score: ",anno1score)
print("Anno2 average score: ",anno2score)
print("AnnoMean average score: ",annomeanscore)

GPT vs Anno1 Spearman:  0.7480042016806723
GPT vs Anno2 Spearman:  0.7668067226890757
Anno1 vs Anno2 Spearman:  0.898529411764706
GPT vs AnnoMean Spearman:  0.7320378151260505
Baseline vs Anno1 Spearman:  0.2008403361344538
Baseline vs Anno2 Spearman:  0.2622899159663866
Baseline vs AnnoMean Spearman:  0.1631302521008403
GPT average score:  [2.83529412 2.8        2.84705882 2.83529412 2.41176471 2.78823529
 2.69411765]
Anno1 average score:  [2.92941176 2.90588235 2.83529412 2.89411765 2.32941176 2.71764706
 2.51764706]
Anno2 average score:  [2.90588235 2.87058824 2.87058824 2.87058824 2.29411765 2.71764706
 2.64705882]
AnnoMean average score:  [2.91764706 2.88823529 2.85294118 2.88235294 2.31176471 2.71764706
 2.58235294]


In [8]:
spearmans =np.zeros([6,6,length])
for j in range(length):
    i = idexls[j]
    human_anno = np.array(list(oc[i]['human_anno'].values()))
    human_anno[:,1:][human_anno[:,1:] == 2] = 1
    human_anno[:,1:][human_anno[:,1:] == 3] = 2
    human_anno[:,1:][human_anno[:,1:] == 5] = 3
    human_anno[:,1:][human_anno[:,1:] == 4] = 3
    for k in range(human_anno.shape[1]):
        for l in range(human_anno.shape[1]):
            spearmans[k,l,j] = calculate_spearman_manual(human_anno[:,k],human_anno[:,l])

print(spearmans.mean(axis=2))

[[1.         0.77930672 0.78718487 0.70966387 0.78119748 0.63529412]
 [0.77930672 1.         0.89852941 0.90577731 0.94096639 0.66386555]
 [0.78718487 0.89852941 1.         0.84012605 0.95966387 0.66218487]
 [0.70966387 0.90577731 0.84012605 1.         0.8717437  0.6414916 ]
 [0.78119748 0.94096639 0.95966387 0.8717437  1.         0.67331933]
 [0.63529412 0.66386555 0.66218487 0.6414916  0.67331933 1.        ]]
